name: Build Changelog

on:
  push:
    tags:
      - '*'

jobs:
  build_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3.7.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
